### ISSUE TITLE
server end closed, client end stuck in write_pending()

### ISSUE THREAD

**Issue by gopakumarce** [snapview/tungstenite-rs#183]
Hi,

I make a client connection like this ```tungstenite::client(request.body(()).unwrap(), connected_stream)``` where the connected_stream is a tcp+tls session. the connection establishes all good, I can exchange data etc.. fine. Also note that the connected_stream is in non-blocking mode. Now on the server i just restart the process and I assume that would terminate the tcp session and somehow the tunstenite client would come to know of that (tcpStream read would return error maybe ?). But I see that the tungstenite client is stuck in a loop trying to write pending messages and it never gets out of it

```
Thread 1 (Thread 0x7ffff7fd1800 (LWP 2581830)):
#0  0x0000555555598108 in tungstenite::protocol::WebSocketContext::write_pending (self=0x7fffffffd368, stream=0x7fffffffd358)
    at /home/gopa/.cargo/registry/src/github.com-1ecc6299db9ec823/tungstenite-0.13.0/src/protocol/mod.rs:371
#1  0x000055555559a8e8 in tungstenite::protocol::WebSocketContext::close (self=0x7fffffffd368, stream=0x7fffffffd358, code=...)
    at /home/gopa/.cargo/registry/src/github.com-1ecc6299db9ec823/tungstenite-0.13.0/src/protocol/mod.rs:420
#2  0x000055555559ab8f in tungstenite::protocol::WebSocket<Stream>::close (self=0x7fffffffd358, code=...)
    at /home/gopa/.cargo/registry/src/github.com-1ecc6299db9ec823/tungstenite-0.13.0/src/protocol/mod.rs:223
#3  0x00005555555959a1 in <websock::WebSession as common::Transport>::read (self=0x7fffffffd2e8) at /home/gopa/.cargo/git/checkouts/common-f662b7f9b5f3458c/91c8c49/rust/transport/websocket/src/lib.rs:148
#4  0x000055555557f452 in docker::gwtun_rx (gw_tun=...) at /home/gopa/NXT/agent/rust/platforms/docker/src/main.rs:106
#5  0x0000555555580553 in docker::main () at /home/gopa/NXT/agent/rust/platforms/docker/src/main.rs:176
(gdb) 
```

**Comment by gopakumarce** [comment]
never mind .. i was doing something messed up, my apologies

**Comment by gkristjansson** [comment]
@gopakumarce what so going on ? I have something appears similar.
