### ISSUE TITLE
Connection fails with release 0.14

### ISSUE THREAD

**Issue by sanpii** [snapview/tungstenite-rs#216]
Hello,

This simple code works fine with tungstenite 0.13 but fails with 0.14:
```rust
fn main() {
    let token = "eyJhbGciOiJIUzUxMiIsInR5cCI6IkpXVCJ9";
    let url = format!(
        "wss://api.captainfact.io/socket/websocket?token={}&vsn=2.0.0",
        token
    );

    tungstenite::connect(&url).unwrap();
}
```
```
$ RUST_BACKTRACE=1 cg r
    Finished dev [unoptimized + debuginfo] target(s) in 0.01s
     Running `target/debug/nix-bug`
thread 'main' panicked at 'called `Result::unwrap()` on an `Err` value: Url(UnableToConnect("wss://api.captainfact.io/socket/websocket?token=eyJhbGciOiJIUzUxMiIsInR5cC
I6IkpXVCJ9&vsn=2.0.0"))',
src/main.rs:8:32stack backtrace:
   0: rust_begin_unwind
             at /rustc/53cb7b09b00cbea8754ffb78e7e3cb521cb8af4b/library/std/src/panicking.rs:493:5
   1: core::panicking::panic_fmt
             at /rustc/53cb7b09b00cbea8754ffb78e7e3cb521cb8af4b/library/core/src/panicking.rs:92:14
   2: core::result::unwrap_failed
             at /rustc/53cb7b09b00cbea8754ffb78e7e3cb521cb8af4b/library/core/src/result.rs:1355:5
   3: core::result::Result<T,E>::unwrap
             at /home/sanpi/.rustup/toolchains/stable-x86_64-unknown-linux-gnu/lib/rustlib/src/rust/library/core/src/result.rs:1037:23
   4: nix_bug::main
             at ./src/main.rs:8:5
   5: core::ops::function::FnOnce::call_once
             at /home/sanpi/.rustup/toolchains/stable-x86_64-unknown-linux-gnu/lib/rustlib/src/rust/library/core/src/ops/function.rs:227:5
note: Some details are omitted, run with `RUST_BACKTRACE=full` for a verbose backtrace.
```

**Comment by application-developer-DA** [comment]
Hi, this is because we don't have the tls enabled anymore as the default feature (see #202), so it can't connect to the WSS endpoint. You can make it work if you activate the `rustls-tls` or `native-tls` feature (I've just tested it with `rustls-tls` and it worked fine). Hope this helps.

**Comment by sanpii** [comment]
Thank you, it’s work fine now!

It could be helpful to have this information in the error message.
